-- =========================================================================
-- PHẦN 1: DỌN DẸP LÀM SẠCH DATABASE
-- =========================================================================
drop table LICH_SU_KHO cascade constraints;
drop table CTHD cascade constraints;
drop table HOADON cascade constraints;
drop table CALAM cascade constraints;
drop table KHACHHANG cascade constraints;
drop table SANPHAM cascade constraints;
drop table NHANVIEN cascade constraints;

-- =========================================================================
-- PHẦN 2: KHỞI TẠO CÁC BẢNG DANH MỤC CỐT LÕI
-- =========================================================================

-- 1. BẢNG NHÂN VIÊN
create table NHANVIEN (
    id number generated by default as identity primary key,
    hoten varchar2(100) not null,
    sdt varchar2(15),
    mkdangnhap varchar2(255) not null,
    vaitro varchar2(20) default 'NHANVIEN', 
    trangthai number(1) default 1
);

-- 2. BẢNG KHÁCH HÀNG (Sử dụng ID làm PK, SĐT làm Unique)
create table KHACHHANG (
    id number generated by default as identity primary key, 
    sdt varchar2(15) unique not null,                       
    hoten varchar2(100),
    diemtichluy number default 0,
    ngaytao date default sysdate
);

-- 3. BẢNG SẢN PHẨM (Tích hợp chốt chặn an toàn kho)
create table SANPHAM (
    id number generated by default as identity primary key,
    ten varchar2(100) not null,
    category varchar2(50),
    giaban number(15, 2) not null,
    tonkho number default 0,
    imageurl varchar2(255),
    is_deleted number(1) default 0,
    constraint chk_tonkho_positive check (tonkho >= 0) 
);

-- =========================================================================
-- PHẦN 3: CÁC BẢNG NGHIỆP VỤ PHÁT SINH
-- =========================================================================

-- 4. BẢNG LỊCH SỬ KHO (Trung tâm điều khiển kho)
create table LICH_SU_KHO (
    id number generated by default as identity primary key,
    sanpham_id number not null,
    loai_phieu varchar2(50),      
    so_luong number not null,     
    tonkho_sau number default 0 not null, -- Mặc định 0, Trigger sẽ tự tính toán đè lên
    nguoi_thuc_hien number,       
    ngay_tao timestamp default systimestamp,
    ghi_chu varchar2(255),
    constraint fk_lsk_sp foreign key (sanpham_id) references SANPHAM(id)
);

-- 5. BẢNG CA LÀM (Tích hợp may_pos dạng số)
create table CALAM (
    id number generated by default as identity primary key,
    nhanvien_id number not null,
    may_pos number default 1 not null, -- Số định danh máy (1, 2, 3...)
    batdau timestamp default systimestamp,
    ketthuc timestamp,
    tienmat_bandau number(15, 2) default 0,
    tienmat_ketca number(15, 2) default 0, 
    tien_nganhang number(15, 2) default 0, 
    tien_mat number(15, 2) default 0, 
    tong_doanhthu number(15, 2) default 0, 
    tongtien_thucte number(15, 2) default 0, 
    ghichu varchar2(255),
    constraint fk_calam_nv foreign key (nhanvien_id) references NHANVIEN(id)
);

-- 6. BẢNG HÓA ĐƠN
create table HOADON (
    id varchar2(20) primary key,
    nhanvien_id number not null,
    khachhang_id number,            
    calam_id number not null,       
    ngaylap timestamp default systimestamp,
    tongtien number(15, 2) not null,
    giamgia number(15, 2) default 0,
    phuongthuc_tt varchar2(20), 
    trangthai varchar2(20) default 'HOAN_THANH',
    constraint fk_hd_nv foreign key (nhanvien_id) references NHANVIEN(id),
    constraint fk_hd_kh foreign key (khachhang_id) references KHACHHANG(id),
    constraint fk_hd_cl foreign key (calam_id) references CALAM(id)
);

-- 7. CHI TIẾT HÓA ĐƠN
create table CTHD (
    hoadon_id varchar2(20) not null,
    sanpham_id number not null,
    soluong number not null,
    dongia number(15, 2) not null,
    primary key (hoadon_id, sanpham_id),
    constraint fk_cthd_hd foreign key (hoadon_id) references HOADON(id),
    constraint fk_cthd_sp foreign key (sanpham_id) references SANPHAM(id)
);

-- =========================================================================
-- PHẦN 4: INDEX TỐI ƯU HIỆU NĂNG TÌM KIẾM
-- =========================================================================
create index idx_sp_ten on SANPHAM(ten);
create index idx_hd_ngay on HOADON(ngaylap);
create index idx_cl_nv on CALAM(nhanvien_id);
create index idx_hd_calam on HOADON(calam_id);
CREATE INDEX idx_lsk_sanpham ON LICH_SU_KHO(sanpham_id);
CREATE INDEX idx_lsk_ngay ON LICH_SU_KHO(ngay_tao);