/*
===============================================================================
FILE: 01_recovery_audit_log_mo_phong.sql
MUC DICH:
  - Mo phong phan Recovery o muc ung dung DBMS theo yeu cau mon hoc.
  - Oracle thuc te co Undo, Redo log, Checkpoint noi bo.
  - Trong do an, ta tao bang log nghiep vu de minh hoa y tuong Undo/Redo/Checkpoint.
  - Khong them cot/khoa ngoai vao 7 bang goc.
===============================================================================
*/

/*
BANG: AUDIT_LOG
MUC DICH:
  - Ghi lai thay doi quan trong de truy vet khi du lieu sai.
  - Khong dung FK de tranh pha schema goc/app.
*/
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE AUDIT_LOG (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            bang_tac_dong VARCHAR2(50) NOT NULL,
            khoa_chinh VARCHAR2(100),
            hanh_dong VARCHAR2(50) NOT NULL,
            gia_tri_cu CLOB,
            gia_tri_moi CLOB,
            nguoi_thuc_hien NUMBER,
            thoi_gian TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            ghi_chu VARCHAR2(500)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

/*
BANG: DBMS_RECOVERY_LOG
MUC DICH:
  - Mo phong Undo/Redo log o muc nghiep vu.
  - BEFORE_VALUE co the xem nhu thong tin phuc vu Undo.
  - AFTER_VALUE co the xem nhu thong tin phuc vu Redo.
  - checkpoint_code dung de danh dau moc phuc hoi.
*/
BEGIN
    EXECUTE IMMEDIATE q'[
        CREATE TABLE DBMS_RECOVERY_LOG (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ten_giao_tac VARCHAR2(100),
            bang_tac_dong VARCHAR2(50),
            khoa_chinh VARCHAR2(100),
            before_value CLOB,
            after_value CLOB,
            checkpoint_code VARCHAR2(100),
            thoi_gian TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
            ghi_chu VARCHAR2(500)
        )
    ]';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

/*
TRIGGER: TRG_AUDIT_HOADON_STATUS
LOI/NGUY CO XU LY:
  - Hoa don doi trang thai do VNPay/job/quan ly.
  - Can truy vet trang thai cu -> moi.
*/
CREATE OR REPLACE TRIGGER TRG_AUDIT_HOADON_STATUS
AFTER UPDATE OF trangthai ON HOADON
FOR EACH ROW
BEGIN
    INSERT INTO AUDIT_LOG(bang_tac_dong, khoa_chinh, hanh_dong, gia_tri_cu, gia_tri_moi, nguoi_thuc_hien, ghi_chu)
    VALUES('HOADON', :NEW.id, 'UPDATE_TRANGTHAI', :OLD.trangthai, :NEW.trangthai, :NEW.nhanvien_id,
           'Audit doi trang thai hoa don');

    INSERT INTO DBMS_RECOVERY_LOG(ten_giao_tac, bang_tac_dong, khoa_chinh, before_value, after_value, checkpoint_code, ghi_chu)
    VALUES('UPDATE_TRANGTHAI_HOADON', 'HOADON', :NEW.id, :OLD.trangthai, :NEW.trangthai,
           'CP_HD_' || TO_CHAR(SYSTIMESTAMP, 'YYYYMMDDHH24MISS'), 'Mo phong undo/redo cho trang thai hoa don');
END;
/

/*
TRIGGER: TRG_AUDIT_SANPHAM_UPDATE
LOI/NGUY CO XU LY:
  - Quan ly sua gia, sua ton kho truc tiep, xoa mem san pham.
  - Can truy vet de giai thich du lieu thay doi.
*/
CREATE OR REPLACE TRIGGER TRG_AUDIT_SANPHAM_UPDATE
AFTER UPDATE ON SANPHAM
FOR EACH ROW
BEGIN
    INSERT INTO AUDIT_LOG(bang_tac_dong, khoa_chinh, hanh_dong, gia_tri_cu, gia_tri_moi, ghi_chu)
    VALUES(
        'SANPHAM',
        TO_CHAR(:NEW.id),
        'UPDATE_SANPHAM',
        'ten=' || :OLD.ten || ', giaban=' || :OLD.giaban || ', tonkho=' || :OLD.tonkho || ', is_deleted=' || :OLD.is_deleted,
        'ten=' || :NEW.ten || ', giaban=' || :NEW.giaban || ', tonkho=' || :NEW.tonkho || ', is_deleted=' || :NEW.is_deleted,
        'Audit thay doi san pham'
    );
END;
/

/*
TRIGGER: TRG_AUDIT_LICHSUKHO_INSERT
LOI/NGUY CO XU LY:
  - Ton kho thay doi nhung khong biet nguon goc.
  - Moi bien dong LICH_SU_KHO duoc ghi audit.
*/
CREATE OR REPLACE TRIGGER TRG_AUDIT_LICHSUKHO_INSERT
AFTER INSERT ON LICH_SU_KHO
FOR EACH ROW
BEGIN
    INSERT INTO AUDIT_LOG(bang_tac_dong, khoa_chinh, hanh_dong, gia_tri_moi, nguoi_thuc_hien, ghi_chu)
    VALUES(
        'LICH_SU_KHO',
        TO_CHAR(:NEW.id),
        'INSERT_BIEN_DONG_KHO',
        'sanpham_id=' || :NEW.sanpham_id || ', loai=' || :NEW.loai_phieu || ', so_luong=' || :NEW.so_luong || ', tonkho_sau=' || :NEW.tonkho_sau,
        :NEW.nguoi_thuc_hien,
        'Audit bien dong kho'
    );
END;
/

/*
PROCEDURE: PROC_TAO_CHECKPOINT_NGHIEP_VU
MUC DICH:
  - Mo phong checkpoint o muc bao cao.
  - Ghi lai mot moc de thuyet minh: sau checkpoint, recovery co the dua he thong ve moc gan nhat.
*/
CREATE OR REPLACE PROCEDURE PROC_TAO_CHECKPOINT_NGHIEP_VU(p_ten_checkpoint IN VARCHAR2)
AS
BEGIN
    INSERT INTO DBMS_RECOVERY_LOG(ten_giao_tac, bang_tac_dong, khoa_chinh, checkpoint_code, ghi_chu)
    VALUES('CHECKPOINT', 'SYSTEM', '-', p_ten_checkpoint, 'Mo phong checkpoint nghiep vu cho bao cao DBMS');
END;
/
