spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:oracula
    username: pos_admin
    password: "589632"
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        jdbc:
          "[fetch_size]": 100
        "[order_inserts]": true
        "[order_updates]": true