-- Xóa bảng cũ để làm sạch (theo thứ tự để tránh lỗi khóa ngoại)
drop table CTHD cascade constraints;
drop table HOADON cascade constraints;
drop table CALAM cascade constraints;
drop table SANPHAM cascade constraints;
drop table KHACHHANG cascade constraints;
drop table NHANVIEN cascade constraints;

-- 1. BẢNG NHÂN VIÊN (Gộp cả Quản lý)
create table NHANVIEN (
    id number generated by default as identity primary key,
    hoten varchar2(100) not null,
    sdt varchar2(15),
    mkdangnhap varchar2(255) not null,
    vaitro varchar2(20) default 'NHANVIEN', -- 'ADMIN' hoặc 'NHANVIEN'
    trangthai number(1) default 1 -- 1: Đang làm, 0: Nghỉ việc
);

-- 2. BẢNG SẢN PHẨM (Gộp cả Kho hàng)
create table SANPHAM (
    id number generated by default as identity primary key,
    ten varchar2(100) not null,
    category varchar2(50),
    giaban number(15, 2) not null,
    tonkho number default 0, -- Gộp từ bảng KHO
    image_url varchar2(255)
);

-- 3. BẢNG KHÁCH HÀNG
create table KHACHHANG (
    sdt varchar2(15) primary key,
    hoten varchar2(100),
    diemtichluy number default 0,
    ngaytao date default sysdate
);

-- 4. BẢNG CA LÀM (Gộp báo cáo kết ca)
create table CALAM (
    id number generated by default as identity primary key,
    nhanvien_id number not null,
    batdau timestamp default systimestamp,
    ketthuc timestamp,
    tienmat_bandau number(15, 2) default 0,
    tienmat_ketca number(15, 2) default 0, -- Số tiền mặt nhân viên thực đếm
    tien_nganhang number(15, 2) default 0, -- Doanh thu từ CK/Momo (hệ thống tính)
    tong_doanhthu number(15, 2) default 0, -- Tổng tiền hệ thống tính (Cash + Bank)
    tongtien_thucte number(15, 2) default 0, -- Tổng thực tế có (Tiền mặt đếm + Bank)
    ghichu varchar2(255),
    constraint fk_calam_nv foreign key (nhanvien_id) references NHANVIEN(id)
);

-- 5. BẢNG HÓA ĐƠN (Gộp thông tin thanh toán)
create table HOADON (
    id varchar2(20) primary key,
    nhanvien_id number not null,
    khach_sdt varchar2(15),
    ngaylap timestamp default systimestamp,
    tongtien number(15, 2) not null,
    giamgia number(15, 2) default 0,
    -- Thông tin thanh toán gộp từ THANHTOAN
    phuongthuc_tt varchar2(20), -- 'TIEN_MAT', 'CHUYEN_KHOAN'
    trangthai varchar2(20) default 'HOAN_THANH',
    constraint fk_hd_nv foreign key (nhanvien_id) references NHANVIEN(id),
    constraint fk_hd_kh foreign key (khach_sdt) references KHACHHANG(sdt)
);

-- 6. CHI TIẾT HÓA ĐƠN
create table CTHD (
    hoadon_id varchar2(20) not null,
    sanpham_id number not null,
    soluong number not null,
    dongia number(15, 2) not null,
    primary key (hoadon_id, sanpham_id),
    constraint fk_cthd_hd foreign key (hoadon_id) references HOADON(id),
    constraint fk_cthd_sp foreign key (sanpham_id) references SANPHAM(id)
);

-- INDEX TỐI ƯU (Chỉ giữ lại những cái thực sự cần thiết)
create index idx_sp_ten on SANPHAM(ten);
create index idx_hd_ngay on HOADON(ngaylap);
create index idx_cl_nv on CALAM(nhanvien_id);